#spring.application.name=image-thumbnail
server:
  port: 8080
  servlet:
    context-path: /thumbnail

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/pi-image"
    username: root
    password: root